autoreload: false
language: javascript
jarDirectory: lib
# Set this to false for jruby, it does not correctly handle scopes, other
# than ENGINE_SCOPE and GLOBAL_SCOPE defined in JSR 223
useScriptScope: true
systemProperties:
    # See https://wiki.openjdk.java.net/display/Nashorn/Nashorn+jsr223+engine+notes
    nashorn.args: ''
    # See https://kenai.com/projects/jruby-embed/pages/Home
    org.jruby.embed.localcontext.scope: 'singleton'
    org.jruby.embed.localvariable.behavior: 'global'
    org.jruby.embed.compilemode: off
#    org.jruby.embed.class.path: 'plugins/EasyScript/ruby'
    # See https://wiki.python.org/jython/Settings
    python.cachedir: 'pythoncachedir'
    python.cachedir.skip: false
#    python.path: plugins/EasyScript/python
libraries:
  - library
scriptPath:
  - scripts
