name: "EasyScript"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.easyscript.EasyScript"
website: "http://dev.bukkit.org/server-mods/easyscript/"
commands:
  spell:
    description: Execute a script
    usage: /spell <name> <args>
    permission: easyscript.script
  scriptreload:
    description: Recompile scripts
    usage: /scriptreload [classpath]
    permission: easyscript.reload
